### ISSUE TITLE
Issue: Export is not defined (`catchjs.es.js:65`)

### ISSUE THREAD

**Issue by Ramanpreet1103** [getcatch/catchjs#21]
Recently faced an issue regarding a export component on this file and line number `catchjs.es.js:65`. I'm trying to resolve that on my own, if i'm able to find the resolution for that, will share here

![Screenshot from 2023-03-16 18-19-55](https://user-images.githubusercontent.com/91800751/225893687-ae184c27-7244-48a9-8bf0-6017a29ce187.png)

**Comment by Ramanpreet1103** [comment]
Please someone assign this to me, as i'm working on it

**Comment by Ramanpreet-hcode** [comment]
Hi there I just looked into the package and was able to find and fix the issue. Since we are using export in the module's js file. So we just need to specify the same in the package.json file. 

Just need to add ` "type": "module"` in `package.json` file

**Comment by LevKanter** [comment]
Hi @Ramanpreet1103, please keep in mind that this module is intended for use in a browser-side program, not in a NodeJS program. Even if the `"type": "module"` allows you to load the module in your program, calling `loadCatchjs` will fail if that's done on the server side.

**Comment by Ramanpreet-hcode** [comment]
Hi @LevKanter We are using HydrogenJS (Shopify's React-based headless commerce stack for frontend). Moreover just wanted to add that I am loading the script using this package in useEffect, which does not run in SSR. So I think SSR is not a problem here.

**Comment by Ramanpreet1103** [comment]
Hi @LevKanter  We are using HydrogenJS (Shopify's React-based headless commerce stack for frontend). Moreover just wanted to add that I am loading the script using this package in useEffect, which does not run in SSR. So I think SSR is not a problem here.

**Comment by LevKanter** [comment]
@Ramanpreet1103 we just published a new version `1.0.23` that has the `"type": "module"`. When you get a chance, can you upgrade to that version and let us know if any issues? Thank you!

**Comment by Ramanpreet1103** [comment]
Hi @LevKanter Thanks for releasing a new version with my proposed solution that early. The Package seems to be working fine for me now, but I am still testing all the use cases.
